d2c-org/d2c-core/base-objects/main/default/objects/Account/fields/DomicileState__c.field-meta.xml
<CustomField>
    <fullName>DomicileState__c</fullName>
    <description>Sourced from CUIC. </description>
    <label>Domicile State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ILH: The credit union or other association the consumer is associated to for the opportunity.</description>
    <label>Affiliation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Affiliation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliation Opportunities</relationshipLabel>
    <relationshipName>AffiliationOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/HealthAssessment__c.field-meta.xml
<CustomField>
    <fullName>HealthAssessment__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Health concerns that may prevent customer from qualifying for a traditional, underwritten life insurance policy. This is a requirement for the needs assessment.</description>
    <inlineHelpText>Are you aware of any medical issues or health concerns that you think would keep you from qualifying for a traditional, underwritten life insurance policy?</inlineHelpText>
    <label>Health Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Health Issues</fullName>
            </value>
            <value>
                <fullName>No Health Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/InsurancePurpose__c.field-meta.xml
<CustomField>
    <fullName>InsurancePurpose__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Need or purpose for the insurance coverage, such as funeral expenses or income replacement. This is a requirement for the needs assessment.</description>
    <label>Insurance Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Final Expenses</fullName>
            </value>
            <value>
                <fullName>Income Replacement</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Undecided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/TobaccoUse__c.field-meta.xml
<CustomField>
    <fullName>TobaccoUse__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Indicates if the consumer uses tobacco, which is utilized for particular product underwriting.</description>
    <label>Tobacco Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-objects/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <description>Abbreviated States  Includes PR,VI,FM,GU</description>
    <masterLabel>States</masterLabel>
</GlobalValueSet>

d2c-org/ilh-sales/rate-page/main/default/classes/ConsumerInfoController.cls
public with sharing class ConsumerInfoController {
    @AuraEnabled(cacheable=true)
    public static Opportunity getOpportunityFieldsData(String opportunityId) {
        Opportunity opp = new Opportunity();

        try {
            if (String.isNotEmpty(opportunityId)) {
                return [SELECT Id, Account.Age__pc, Account.Gender__pc, Account.Salutation, Account.FirstName, Account.LastName, Account.MiddleName, 
                    Account.Suffix, InsurancePurpose__c, HealthAssessment__c, TobaccoUse__c, Affiliation__r.Name, Amount, Account.DomicileState__c FROM Opportunity WHERE Id = : opportunityId LIMIT 1];
            }
        } catch (Exception ex) {
            new ErrorLogger(ex, 'An error occurred while getting consumer info.', 'ConsumerInfoController.cls', opportunityId, 'getOpportunityFieldsData', 
                            null, 'MarketingHistory', null);
        }
        return opp;
    }
}