d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ILH: The credit union or other association the consumer is associated to for the opportunity.</description>
    <label>Affiliation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Affiliation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliation Opportunities</relationshipLabel>
    <relationshipName>AffiliationOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/HealthAssessment__c.field-meta.xml
<CustomField>
    <fullName>HealthAssessment__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Health concerns that may prevent customer from qualifying for a traditional, underwritten life insurance policy. This is a requirement for the needs assessment.</description>
    <inlineHelpText>Are you aware of any medical issues or health concerns that you think would keep you from qualifying for a traditional, underwritten life insurance policy?</inlineHelpText>
    <label>Health Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Health Issues</fullName>
            </value>
            <value>
                <fullName>No Health Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/InsurancePurpose__c.field-meta.xml
<CustomField>
    <fullName>InsurancePurpose__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Need or purpose for the insurance coverage, such as funeral expenses or income replacement. This is a requirement for the needs assessment.</description>
    <label>Insurance Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Final Expenses</fullName>
            </value>
            <value>
                <fullName>Income Replacement</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Undecided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product, product family, or type of insurance based on primary campaign source.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/TobaccoUse__c.field-meta.xml
<CustomField>
    <fullName>TobaccoUse__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Indicates if the consumer uses tobacco, which is utilized for particular product underwriting.</description>
    <label>Tobacco Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>Age based on todays date. If deceased, the age at death.</description>
    <label>Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/CoverageAmount__c.field-meta.xml
<CustomField>
    <fullName>CoverageAmount__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Coverage Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>Gender required by actuaries for insurance premiums.</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/HealthAssessment__c.field-meta.xml
<CustomField>
    <fullName>HealthAssessment__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>Health concerns that may prevent customer from qualifying for a traditional, underwritten life insurance policy.</description>
    <inlineHelpText>Are you aware of any medical issues or health concerns that you think would keep you from qualifying for a traditional, underwritten life insurance policy?</inlineHelpText>
    <label>Health Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Health Issues</fullName>
            </value>
            <value>
                <fullName>No Health Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/InsurancePurpose__c.field-meta.xml
<CustomField>
    <fullName>InsurancePurpose__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Insurance Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Final Expenses</fullName>
            </value>
            <value>
                <fullName>Income Replacement</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Undecided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/PaperKitRequestDate__c.field-meta.xml
<CustomField>
    <fullName>PaperKitRequestDate__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>Date the action was taken in the cart</description>
    <label>Paper Kit Request Date</label>
    <type>Date</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/QuoteRider__c.field-meta.xml
<CustomField>
    <fullName>QuoteRider__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Rider</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/ResidentState__c.field-meta.xml
<CustomField>
    <fullName>ResidentState__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Resident State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/TobaccoUse__c.field-meta.xml
<CustomField>
    <fullName>TobaccoUse__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Tobacco Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-objects/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <description>Abbreviated States  Includes PR,VI,FM,GU</description>
    <masterLabel>States</masterLabel>
</GlobalValueSet>

d2c-org/ilh-sales/rate-page/main/default/classes/ILHQuoteHelper.cls
/***
Copyright: TruStage
Purpose: Helper class for quote object
1.0 - Adam Perschke-Ely   - 1/12/2024  - Created for new D2C Salesfore instance.
***/
public with sharing class ILHQuoteHelper {
     /**
     * Purpose: This method gets quotes related to the given opportunity id
     * @param oppId : Opportunity id to get related quotes
     */
    public List<ResultsWrapper> getQuotes(String oppId) {
        List<Quote> quotes = new List<Quote>();
        List<ResultsWrapper> results = new List<ResultsWrapper>();

        try {
            //Query all quotes related to opportunity
            quotes = [SELECT id, Product__r.Name, Product__r.ProductCode, CoverageAmount__c, Premium__c, Status FROM Quote WHERE OpportunityId =: oppId];

            //Assigning quote values to wrapper instances
            for (Quote q : quotes) {
                ResultsWrapper newWrap = new ResultsWrapper();
                newWrap.quoteId = q.id;
                newWrap.coverage = q?.CoverageAmount__c;
                newWrap.cost = q?.Premium__c;
                newWrap.productName = q?.Product__r?.Name;
                newWrap.productCode = q?.Product__r?.ProductCode;
                newWrap.decision = q?.Status;
                results.add(newWrap);
            }
        } catch (Exception ex) {
            new ErrorLogger(ex, 'An error occured while getting quotes in cart', 'ILHQuoteHelper.cls', oppId, 'getQuotes', null, null, null);
        }
        return results;
    }

    /**
     * Purpose: This method inserts a new quote record on the give opportunity id
     * @param payload : Contains field information to be inserted
     */
    public void insertQuote(Map<String, Object> payload) {
        try {
            Quote newQuote = new Quote();
            newQuote = payloadToQuote(payload, true);//Create new quote object for insert
            insert newQuote;
        } catch (Exception ex) {
            new ErrorLogger(ex, 'An error occured while adding quote to cart', 'ILHQuoteHelper.cls', null, 'insertQuote', null, null, null);
        }
    }

    /**
     * Purpose: This method updates a quote record
     * @param payload : Contains field information to be updated
     */
    public void updateQuote(Map<String, Object> payload) {
        try {
            Quote newQuote = new Quote();
            newQuote = payloadToQuote(payload, false);//Create new quote object for update
            update newQuote;
        } catch (Exception ex) {
            new ErrorLogger(ex, 'An error occured while updating quote', 'ILHQuoteHelper.cls', null, 'updateQuote', null, null, null);
        }
    }

    /**
     * Purpose: This method deletes quote for a given id
     * @param quoteId : Id of quote to delete
     */
    public void deleteQuote(String quoteId) {
        try {
            delete [SELECT id FROM Quote WHERE id =: quoteId];  
        } catch (Exception ex) {
            new ErrorLogger(ex, 'An error occured while removing quote from cart', 'ILHQuoteHelper.cls', quoteId, 'deleteQuote', null, null, null);
        }
    }

    /**
     * Purpose: This method transforms payload into a quote object
     * @param payload : Payload to transform into a quote object
     * @return : New quote object
     */
    private Quote payloadToQuote(Map<String, Object> payload, Boolean isInsert) {
        Quote newQuote = new Quote();
        Opportunity opp = new Opportunity();
        List<Product2> selectedProduct = new List<Product2>();
        Boolean selectedProductFound = false;

        //Get values from map
        String quoteId = (String)payload.get('quoteId');
        String costStr = (String)payload.get('cost');
        String coverageStr = (String)payload.get('coverage');
        String productName = (String)payload.get('productName');
        String productCode = (String)payload.get('productCode');
        String oppId = (String)payload.get('oppId');
        String decision = (String)payload.get('decision');

        //Convert map string values integer or decimal values
        Decimal cost = costStr != null ? Decimal.valueOf(costStr) : 0;
        Integer coverage = coverageStr != null ? Integer.valueOf(coverageStr) : 0;

        //Don't map if don't have an opportunity id from rate page
        if (String.isNotEmpty(oppId)) {
            Date todaysDate = Date.today();
            opp = [SELECT Affiliation__c, Account.Age__pc, Account.PersonBirthdate, Account.Gender__pc, HealthAssessment__c, InsurancePurpose__c, 
                    TobaccoUse__c, Account.PersonMailingState, Account.LastName, Account.PersonHomePhone, Account.PersonEmail, Account.ShippingCity,
                    Account.ShippingCountry, Account.ShippingPostalCode, Account.ShippingState, Account.ShippingStreet FROM Opportunity WHERE id =: oppId];
        }

        //Only map opportunity/account fields on insert only
        if (isInsert) {
            //Find product id based on product code from cart item
            if (String.isNotEmpty(productCode)) {
                selectedProduct = [SELECT id, Name FROM Product2 WHERE ProductCode =: productCode AND IsActive =: true];

                if (selectedProduct != null && !selectedProduct.isEmpty()) {
                    selectedProductFound = true;
                    newQuote.Product__c = selectedProduct[0].id;
                }
            }

            //Don't map if don't have an opportunity id from rate page
            if (opp != null) {
                Date todaysDate = Date.today();
                newQuote.OpportunityId = oppId;
                newQuote.Affiliation__c = opp.Affiliation__c;
                newQuote.Age__c = opp.Account?.Age__pc;
                newQuote.Birthdate__c = opp.Account?.PersonBirthdate;
                newQuote.Gender__c = opp.Account?.Gender__pc;
                newQuote.HealthAssessment__c = opp.HealthAssessment__c;
                newQuote.InsurancePurpose__c = opp.InsurancePurpose__c;
                newQuote.TobaccoUse__c = opp.TobaccoUse__c;
                newQuote.ResidentState__c = opp.Account?.PersonMailingState;
                newQuote.Name = opp.Account?.LastName + '-' + Datetime.now() + '-' + (selectedProductFound ? selectedProduct[0].Name : '');
                newQuote.Phone = opp.Account?.PersonHomePhone;
                newQuote.ShippingCity = opp.Account?.ShippingCity;
                newQuote.ShippingCountry = opp.Account?.ShippingCountry;
                newQuote.ShippingPostalCode	= opp.Account?.ShippingPostalCode;
                newQuote.ShippingState = opp.Account?.ShippingState;
                newQuote.ShippingStreet = opp.Account?.ShippingStreet;
                newQuote.RecordTypeId = Schema.SObjectType.Quote.getRecordTypeInfosByName().get('ILH Sales Quote').getRecordTypeId();
                //newQuote.GrandTotal = TBD;
                //newQuote.ExpirationDate = TBD;
                //newQuote.QuoteRider__c = TBD;
            }

            //Map reamaining quote fields on insert
            newQuote.CoverageAmount__c = coverage;
            newQuote.Premium__c = cost;
        }

        if (String.isNotEmpty(decision)) {
            List<Quote> existingQuote = new List<Quote>();

            //Find if quote exists
            if (String.isNotEmpty(quoteId)) {
                existingQuote = [SELECT Status, Email FROM Quote WHERE id =: quoteId LIMIT 1];
            }

            //Only update request date if status is not paper kit or blank value
            if (decision.equalsIgnoreCase('Paper Kit') && (existingQuote == null || existingQuote.isEmpty() || existingQuote[0]?.Status == null ||
                !existingQuote[0]?.Status.equalsIgnoreCase('Paper Kit'))) {
                newQuote.PaperKitRequestDate__c = Date.today();
            }

            //Map email if decision is Email Summary and person account email is not blank
            if (decision.equalsIgnoreCase('Email Summary') && String.isNotEmpty(opp.Account?.PersonEmail) && 
                (existingQuote == null || existingQuote.isEmpty() || (existingQuote != null && !existingQuote.isEmpty() && String.isEmpty(existingQuote[0]?.Email)))) {
                newQuote.Email = opp.Account?.PersonEmail;
            }
        }

        //Map quote id if available
        if (String.isNotEmpty(quoteId)) {
            newQuote.id = quoteId;
        }

        //Decision gets mapped on update and insert
        newQuote.Status = decision;
        return newQuote;
    }

    /**
     * Purpose: Inner wrapper class for results
     * TODO: This will need to be to a different class
     */
    public class ResultsWrapper {
        @AuraEnabled
        public String quoteId;
        @AuraEnabled
        public String oppId;
        @AuraEnabled
        public String productName;
        @AuraEnabled
        public String productCode;
        @AuraEnabled
        public Decimal coverage;
        @AuraEnabled
        public Decimal cost;
        @AuraEnabled
        public String decision;
    }
}