d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/HealthAssessment__c.field-meta.xml
<CustomField>
    <fullName>HealthAssessment__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Health concerns that may prevent customer from qualifying for a traditional, underwritten life insurance policy. This is a requirement for the needs assessment.</description>
    <inlineHelpText>Are you aware of any medical issues or health concerns that you think would keep you from qualifying for a traditional, underwritten life insurance policy?</inlineHelpText>
    <label>Health Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Health Issues</fullName>
            </value>
            <value>
                <fullName>No Health Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/InsurancePurpose__c.field-meta.xml
<CustomField>
    <fullName>InsurancePurpose__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Need or purpose for the insurance coverage, such as funeral expenses or income replacement. This is a requirement for the needs assessment.</description>
    <label>Insurance Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Final Expenses</fullName>
            </value>
            <value>
                <fullName>Income Replacement</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Undecided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/ProposedCoverage__c.field-meta.xml
<CustomField>
    <fullName>ProposedCoverage__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>if applicable, the amount of coverage targeted in the primary campaign source</description>
    <label>Proposed Coverage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/TobaccoUse__c.field-meta.xml
<CustomField>
    <fullName>TobaccoUse__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Indicates if the consumer uses tobacco, which is utilized for particular product underwriting.</description>
    <label>Tobacco Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/HealthAssessment__c.field-meta.xml
<CustomField>
    <fullName>HealthAssessment__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>Health concerns that may prevent customer from qualifying for a traditional, underwritten life insurance policy.</description>
    <inlineHelpText>Are you aware of any medical issues or health concerns that you think would keep you from qualifying for a traditional, underwritten life insurance policy?</inlineHelpText>
    <label>Health Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Health Issues</fullName>
            </value>
            <value>
                <fullName>No Health Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/InsurancePurpose__c.field-meta.xml
<CustomField>
    <fullName>InsurancePurpose__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Insurance Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Final Expenses</fullName>
            </value>
            <value>
                <fullName>Income Replacement</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Undecided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/TobaccoUse__c.field-meta.xml
<CustomField>
    <fullName>TobaccoUse__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Tobacco Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/navigate-quote/main/default/classes/ILHOptyStageValidationTest.cls
/*
Purpose: This is test class for before Save record trigger flow ILH_Opportunity_Stage_Validation_Before_Save

*/
@isTest
public class ILHOptyStageValidationTest {
	
    @isTest
    static void testOpptyStageValidationWithRequiredFields() {
        // Create test opportunity with required fields populated
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Quote',
            HealthAssessment__c='Health Issues',
            InsurancePurpose__c='Final Expenses',
            TobaccoUse__c='No',
            CloseDate = System.today(),
            ProposedCoverage__c = 5000
        );
        insert testOpportunity;

        // Create an instance of the flow
        Map<String, Object> inputVariables = new Map<String, Object>();
        inputVariables.put('recordId', testOpportunity);

        // Start the flow
        Flow.Interview BeforeSaveFlow = new Flow.interview.ILH_Opportunity_Stage_Validation_Before_Save(inputVariables);
        BeforeSaveFlow.start();
        
        // Check if opportunity Stage got updated to Quote
        Opportunity updatedOpportunity = [SELECT Id, StageName FROM Opportunity WHERE Id = :testOpportunity.Id];
        System.assertEquals('Quote', updatedOpportunity.StageName);
        
       
    }

    @isTest
    static void testOpptyStageValidationWithoutRequiredFields() {
        // Create test opportunity without required fields
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Needs Assessment',
            CloseDate = System.today()
            // omitting HealthAssessment__c, InsurancePurpose__c, TobaccoUse__c, ProposedCoverage__c
        );
        insert testOpportunity;

        // Create an instance of the flow
        Map<String, Object> inputVariables = new Map<String, Object>();
        inputVariables.put('recordId', testOpportunity.Id);

        // Start the flow
        Flow.Interview BeforeSaveFlow = new Flow.interview.ILH_Opportunity_Stage_Validation_Before_Save(inputVariables);
        BeforeSaveFlow.start();
        
        // Check if opportunity Stage remains the same (Needs Assessment)
        Opportunity updatedOpportunity = [SELECT Id, StageName,Name FROM Opportunity WHERE Id = :testOpportunity.Id];
        System.assertNotEquals('not Quote', updatedOpportunity.StageName);
    }
    
    @isTest
    static void testOpptyStageValidationNYWithRequiredFields() {
        //create test account
        Account acc = new Account();
        acc.Name = 'Test account';
        acc.PersonMailingState ='NY';
        
        // Create test opportunity with required fields populated
 		Opportunity opptyNY = new Opportunity();
        opptyNY.Name ='Test Opty';
        opptyNY.StageName = 'Quote';
        opptyNY.AccountId = acc.Id;
        opptyNY.HealthAssessment__c = 'Health Issues';
        opptyNY.InsurancePurpose__c = 'Final Expenses';
        opptyNY.TobaccoUse__c = 'No';
        opptyNY.ProposedCoverage__c = 10000;
        opptyNY.CloseDate = System.today();
        
        insert opptyNY;

        // Create an instance of the flow
        Map<String, Object> inputVariables = new Map<String, Object>();
        inputVariables.put('recordId', opptyNY.Id);

        // Start the flow
        Flow.Interview BeforeSaveFlow = new Flow.interview.ILH_Opportunity_Stage_Validation_Before_Save(inputVariables);
        BeforeSaveFlow.start();
        
        // Check if opportunity Stage got updated to Quote
        Opportunity updatedOpportunity = [SELECT Id, StageName FROM Opportunity WHERE Id = :opptyNY.Id];
        System.assertEquals('Quote', updatedOpportunity.StageName);
        
       
    }
    
    @isTest
    static void testOpptyStageValidationNYWithoutRequiredField() {
        //create test account
        Account acc = new Account();
        acc.Name = 'Test account';
        acc.PersonMailingState ='';
        
        // Create test opportunity with required fields populated
 		Opportunity opptyNY = new Opportunity();
        opptyNY.Name ='Test Opty';
        opptyNY.StageName = 'Quote';
        opptyNY.AccountId = acc.Id;
        opptyNY.HealthAssessment__c = 'Health Issues';
        opptyNY.InsurancePurpose__c = 'Final Expenses';
        opptyNY.TobaccoUse__c = 'No';
        opptyNY.ProposedCoverage__c = 10000;
        opptyNY.CloseDate = System.today();
        
        insert opptyNY;

        // Create an instance of the flow
        Map<String, Object> inputVariables = new Map<String, Object>();
        inputVariables.put('recordId', opptyNY);

        // Start the flow
        Flow.Interview BeforeSaveFlow = new Flow.interview.ILH_Opportunity_Stage_Validation_Before_Save(inputVariables);
        BeforeSaveFlow.start();
        
        // Check if opportunity Stage got updated to Quote
        Opportunity updatedOpportunity = [SELECT Id, StageName FROM Opportunity WHERE Id = :opptyNY.Id];
        System.assertNotEquals('not Quote', updatedOpportunity.StageName);
        
        
    }
}