d2c-org/ilh-sales/base-code/main/default/objects/DIConsumerContainer__mdt/DIConsumerContainer__mdt.object-meta.xml
<CustomObject>
    <description>Used in dependency injection framework. This object represents the dependencies in the DI Container. Label = Name of service. Name = Unique name for record.</description>
    <label>DI Consumer Container</label>
    <pluralLabel>DI Consumer Containers</pluralLabel>
</CustomObject>

d2c-org/ilh-sales/base-code/main/default/objects/DIConsumerContainer__mdt/fields/Dependencies__c.field-meta.xml
<CustomField>
    <fullName>Dependencies__c</fullName>
    <description>This field refers to the kind of dependencies this container relies on. Separate multiple values with a comma.</description>
    <inlineHelpText>This field refers to the kind of dependencies this container relies on. Separate multiple values with a comma.</inlineHelpText>
    <label>Dependencies</label>
    <type>TextArea</type>
</CustomField>

d2c-org/ilh-sales/base-code/main/default/objects/InterfaceImplementations__mdt/InterfaceImplementations__mdt.object-meta.xml
<CustomObject>
    <description>Used in dependency injection framework.  This object represents each concrete implementation of the dependency.</description>
    <label>Interface Implementations</label>
    <pluralLabel>Interface Implementations</pluralLabel>
</CustomObject>

d2c-org/ilh-sales/base-code/main/default/objects/InterfaceImplementations__mdt/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <description>The name of a concrete Apex class that implements a given interface.</description>
    <inlineHelpText>The name of a concrete Apex class that implements a given interface.</inlineHelpText>
    <label>Implementation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/ilh-sales/consumer-update/main/default/classes/ILHConsumerUpdateFactory.cls
/**
 * Copyright: TruStage
 * Purpose: Constructs instances of concrete classes that implement designated interfaces based off of the calulated persona.
 */
public class ILHConsumerUpdateFactory {

    /**
     * Purpose: Gets all concrete class instances that implement interfaces that are designated in the "Interface Implementations" custom metadata.
     * @return All instances of concrete class, each of which implements the interface designated in the "Interface Implementations" custom metadata.
     */
    public static List<IConsumerUpdateService> getInstances() {
        return new ILHConsumerUpdateFactory().constructInstances();
    }

    /**
     * Purpose: Instantiates and returns all concrete class instances that implement interfaces
     * that are designated in the "Interface Implementations" custom metadata based on the calculated persona.
     * @return All instances of concrete class, each of which implements the interface designated in the "Interface Implementations" custom metadata.
     */
    private List<IConsumerUpdateService> constructInstances() {
        String persona = ILHPersona.getPersona('ILHConsumerUpdateFactory');
        List<IConsumerUpdateService> classInstances = new List<IConsumerUpdateService>();

        //Get an instance of the persona from the consumer container
        DIConsumerContainer__mdt instanceContainer = DIConsumerContainer__mdt.getInstance(persona);

        //Loop through each dependency in the consumer container
        for (String dep : instanceContainer.Dependencies__c.split(',')) {
            //Get the instance of the dependency from interface implementations
            InterfaceImplementations__mdt implementation = InterfaceImplementations__mdt.getInstance(dep);

            //Add a new instance of the implementations to the list
            classInstances.add((IConsumerUpdateService)Type.forName(implementation.Implementation__c).newInstance());
        }
        return classInstances;
    }
}