d2c-org/ilh-sales/base-code/main/default/objects/DIConsumerContainer__mdt/DIConsumerContainer__mdt.object-meta.xml
<CustomObject>
    <description>Used in dependency injection framework. This object represents the dependencies in the DI Container. Label = Name of service. Name = Unique name for record.</description>
    <label>DI Consumer Container</label>
    <pluralLabel>DI Consumer Containers</pluralLabel>
</CustomObject>

d2c-org/ilh-sales/base-code/main/default/objects/DIConsumerContainer__mdt/fields/Dependencies__c.field-meta.xml
<CustomField>
    <fullName>Dependencies__c</fullName>
    <description>This field refers to the kind of dependencies this container relies on. Separate multiple values with a comma.</description>
    <inlineHelpText>This field refers to the kind of dependencies this container relies on. Separate multiple values with a comma.</inlineHelpText>
    <label>Dependencies</label>
    <type>TextArea</type>
</CustomField>

d2c-org/ilh-sales/base-code/main/default/objects/InterfaceImplementations__mdt/InterfaceImplementations__mdt.object-meta.xml
<CustomObject>
    <description>Used in dependency injection framework.  This object represents each concrete implementation of the dependency.</description>
    <label>Interface Implementations</label>
    <pluralLabel>Interface Implementations</pluralLabel>
</CustomObject>

d2c-org/ilh-sales/base-code/main/default/objects/InterfaceImplementations__mdt/fields/Implementation__c.field-meta.xml
<CustomField>
    <fullName>Implementation__c</fullName>
    <description>The name of a concrete Apex class that implements a given interface.</description>
    <inlineHelpText>The name of a concrete Apex class that implements a given interface.</inlineHelpText>
    <label>Implementation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/ilh-sales/conversion-eligible-quote/main/default/classes/ILHConversionEligibleQuoteFactory.cls
/**********************************************************************************
 * Title:  ILHConversionEligibleQuoteFactory
 * Date:   Jan 2024
 * 
 * Description: Constructs instances of concrete classes that implement designated interfaces based off of the calulated persona.  
 * 
 *************************************************************************************/

public  class ILHConversionEligibleQuoteFactory {
    
    /***
    * Gets all concrete class instances that implement interfaces that are designated in the "Interface Implementations" custom metadata.
    * @return All instances of concrete class, each of which implements the interface designated in the "Interface Implementations" custom metadata.
    */
   public static List<IConversionEligible> getInstances() {
       return new ILHConversionEligibleQuoteFactory().constructInstances();
   }

   /***
    * Instantiates and returns all concrete class instances that implement interfaces that are designated in the "Interface Implementations" 
    * custom metadata based on the calculated persona.
    * @return All instances of concrete class, each of which implements the interface designated in the "Interface Implementations" custom metadata.
    */
   private List<IConversionEligible> constructInstances() {
       List<IConversionEligible> classInstances = new List<IConversionEligible>();
       //String persona = ILHPersona.getPersona('ILHProductQuoteFactory');
       String persona = 'ILH_CSCEQuote';

       //Get an instance of the persona from the consumer container
       DIConsumerContainer__mdt instanceContainer = DIConsumerContainer__mdt.getInstance(persona);

       //Loop through each dependency in the consumer container
       for (String dep : instanceContainer.Dependencies__c.split(',')) {
           //Get the instance of the dependency from interface implementations
           InterfaceImplementations__mdt implementation = InterfaceImplementations__mdt.getInstance(dep);

           //Add a new instance of the implementations to the list
           classInstances.add((IConversionEligible)Type.forName(implementation.Implementation__c).newInstance());
       }
       return classInstances;
   }
}