d2c-org/ilh-sales/base-code/main/default/objects/DIConsumerContainer__mdt/DIConsumerContainer__mdt.object-meta.xml
<CustomObject>
    <description>Used in dependency injection framework. This object represents the dependencies in the DI Container. Label = Name of service. Name = Unique name for record.</description>
    <label>DI Consumer Container</label>
    <pluralLabel>DI Consumer Containers</pluralLabel>
</CustomObject>

d2c-org/ilh-sales/base-code/main/default/objects/DIConsumerContainer__mdt/fields/Dependencies__c.field-meta.xml
<CustomField>
    <fullName>Dependencies__c</fullName>
    <description>This field refers to the kind of dependencies this container relies on. Separate multiple values with a comma.</description>
    <inlineHelpText>This field refers to the kind of dependencies this container relies on. Separate multiple values with a comma.</inlineHelpText>
    <label>Dependencies</label>
    <type>TextArea</type>
</CustomField>

d2c-org/ilh-sales/base-code/main/default/objects/DIConsumerContainer__mdt/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <description>Persona assigned to user</description>
    <inlineHelpText>Persona assigned to user</inlineHelpText>
    <label>Persona</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/ilh-sales/base-code/main/default/classes/ILHUtilities.cls
/**
 * Copyright: TruStage
 * Purpose: This class contains ILH Utility methods
 */
public with sharing class ILHUtilities {
    /**
     * Purpose: This method get DI Consumer containers by persona
     * @param persona Name of persona to search on
     * @return List of containers
     */
    public static List<DIConsumerContainer__mdt> getDIConsumerContainer(String persona, String factory) {
        List<DIConsumerContainer__mdt> containers = new List<DIConsumerContainer__mdt>();

        try {
            containers = [SELECT MasterLabel, DeveloperName, Dependencies__c, Persona__c FROM DIConsumerContainer__mdt WHERE Persona__c =: persona AND MasterLabel =: factory];
        } catch (Exception ex) {
            new ErrorLogger(ex, null, 'ILHUtilities.cls', null, 'getDIConsumerContainer', null, null, null);
        }
        return containers;
    }
}