d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/ExceptionLog__e.object-meta.xml
<CustomObject>
    <description>Error log for tracking platform errors.</description>
    <label>Exception Log</label>
    <pluralLabel>Exception Logs</pluralLabel>
</CustomObject>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/CurrentUser__c.field-meta.xml
<CustomField>
    <fullName>CurrentUser__c</fullName>
    <description>Id of user that triggered the error.</description>
    <inlineHelpText>Id of user that triggered the error.</inlineHelpText>
    <label>Current User</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ErrorDescription__c.field-meta.xml
<CustomField>
    <fullName>ErrorDescription__c</fullName>
    <description>Detailed description of error.</description>
    <inlineHelpText>Detailed description of error.</inlineHelpText>
    <label>Error Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Type of operation that was preformed when the error occurred.</description>
    <label>Operation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <description>Indicates where the error originated.</description>
    <inlineHelpText>Indicates where the error originated.</inlineHelpText>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <description>Id of record that triggered the error.</description>
    <inlineHelpText>Id of record that triggered the error.</inlineHelpText>
    <label>Reference Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/RequestData__c.field-meta.xml
<CustomField>
    <fullName>RequestData__c</fullName>
    <description>Data that was entered by user when the error occurred.</description>
    <label>Request Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <description>Status from callout.</description>
    <label>Response Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <description>Name of the service that was called when the error occurred.</description>
    <label>Service Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>The stack trace of a thrown exception</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/TypeOfError__c.field-meta.xml
<CustomField>
    <fullName>TypeOfError__c</fullName>
    <description>Describes the error type.</description>
    <label>Type Of Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/classes/ErrorLogger.cls
/**
*****************************************************************************************************
Apex Class Name    : ErrorLogger
Created Date       : September 26, 2023
@description       : The purpose of this class is to consume an error and create a new exception log
@author            : Adam Perschke-Ely
Modification Log:
Ver   Date         Author                               Modification
1.0   09-26-2023   Adam Perschke-Ely                   Initial Version
*****************************************************************************************************
*/
public with sharing class ErrorLogger {
    private static final Boolean ERROR_LOGS_ENABLED = Boolean.valueOf(System.Label.EnableErrorLogs);

	@InvocableVariable
	public String processName;
	@InvocableVariable
	public String recordId;
	@InvocableVariable
	public String operation;
	@InvocableVariable
	public String requestData;
	@InvocableVariable
	public String serviceName;
	@InvocableVariable
	public String errorDescription;
	@InvocableVariable
	public String stackTrace;
	@InvocableVariable
	public String typeOfError;
	private Exception ex;
	private String strErrorMsg;
	private Integer responseCode;

	/**
	 * Default constructor
	 */
	public ErrorLogger() {}

	/**
    ***************************************************************************************************************************************
	@author         : Adam Perschke-Ely
    @description    : This method maps input values to variables.
	@param ex : Exception from where error originated.
    @param processName   : Indicates where the error originated.
	@param strErrorMsg   : Detailed description of error.
	@param recordId   : Id of record that triggered the error.
	@param operation : Type of operation that was preformed when the error occurred.
	@param requestData : Data that was entered by user when the error occurred.
	@param serviceName : Name of the service that was called when the error occurred.
	@param responseCode : Status from callout.
    ***************************************************************************************************************************************
    */
	public ErrorLogger(Exception ex, String strErrorMsg, string processName, string recordId, String operation, String requestData, String serviceName, 
						Integer responseCode) {
		this.ex = ex;
		this.strErrorMsg = strErrorMsg;
		this.processName = processName;
		this.recordId = recordId;
		this.operation = operation;
		this.requestData = requestData;
		this.serviceName = serviceName;
		this.responseCode = responseCode;
		this.errorDescription = ex?.getMessage();
		this.stackTrace = ex?.getStackTraceString();
		this.typeOfError = ex?.getTypeName();
		this.publishException();
	}

	/**
    ***************************************************************************************************************************************
    @Method Name    : handleError
    @author         : Adam Perschke-Ely
    @description    : This method accepts error log information from a flow.
	@param logs : List of error logs from flow. Should only be one record.
    ***************************************************************************************************************************************
    */
	@InvocableMethod(label='Handle Errors')
	public static void handleError(List<ErrorLogger> logs) {
		logs[0].publishException();
	}

	/**
    ***************************************************************************************************************************************
    @Method Name    : publishException
    @author         : Adam Perschke-Ely
    @description    : This method publishes an exception record. ErrorLogEventHandler will create the error log record on the custom object
    ***************************************************************************************************************************************
    */
	public void publishException() {
		if((String.isNotEmpty(processName) || String.isNotEmpty(recordId) || String.isNotEmpty(operation) || String.isNotEmpty(requestData) || 
			String.isNotEmpty(serviceName) || String.isNotEmpty(errorDescription) || String.isNotEmpty(stackTrace) || String.isNotEmpty(typeOfError) || 
			responseCode != null) && ERROR_LOGS_ENABLED) {
			ExceptionLog__e logRecord = new ExceptionLog__e();
			
			logRecord.ErrorDescription__c = errorDescription;
			logRecord.ProcessName__c = processName;
			logRecord.ReferenceID__c = recordId;
			logRecord.CurrentUser__c = UserInfo.getUserId();
			logRecord.Operation__c = operation;
			//logRecord.RequestData__c = requestData;TODO: Will enable once we decide on a way to remove sensive data from the request.
			logRecord.ServiceName__c = serviceName;
			logRecord.StackTrace__c	= stackTrace;
			logRecord.TypeOfError__c = typeOfError;
			logRecord.ResponseCode__c = responseCode;
			
			eventBus.publish(logRecord);
		}

		// If the error is set to an error that is already thrown it will not be displayed again.
		if(String.isNotEmpty(strErrorMsg)) {
			throw new handleCaughtErrorException(strErrorMsg);
		}
    }

	/** instance of a new exception for use within this class only **/
	public class handleCaughtErrorException extends Exception {} 
}