d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/API_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>Store the rest/soap api endpoint information like method,URL,named credentials, timeout etc</description>
    <label>API Endpoint</label>
    <pluralLabel>API Endpoints</pluralLabel>
</CustomObject>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>Client id</description>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>application/json</fullName>
                <default>true</default>
                <label>application/json</label>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>text/xml; charset=utf-8</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/is_Active__c.field-meta.xml
<CustomField>
    <fullName>is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether this endpoint is active or not</description>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/isOIDCSecured__c.field-meta.xml
<CustomField>
    <fullName>isOIDCSecured__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field tells whether endpoints are OIDC secured and need JWT for authentication</description>
    <label>is OIDC Secured</label>
    <type>Checkbox</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Mock_Response_Static_Resource__c.field-meta.xml
<CustomField>
    <fullName>Mock_Response_Static_Resource__c</fullName>
    <label>Mock Response Static Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>Which named credential to use</description>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Service_Method__c.field-meta.xml
<CustomField>
    <fullName>Service_Method__c</fullName>
    <label>Service Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>ServiceName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/SOAP_Method__c.field-meta.xml
<CustomField>
    <fullName>SOAP_Method__c</fullName>
    <label>SOAP Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
                <default>true</default>
                <label>REST</label>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/APIEnvironmentSFOrgID__mdt/APIEnvironmentSFOrgID__mdt.object-meta.xml
<CustomObject>
    <description>Used to manage the SF org to connect to dev/demo/e01/prod environments.</description>
    <label>API Environment SF Org ID</label>
    <pluralLabel>API Environment SF Org IDs</pluralLabel>
</CustomObject>

d2c-org/d2c-core/base-code/main/default/objects/APIEnvironmentSFOrgID__mdt/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <description>Dev/demo/e01/prod</description>
    <label>Environment</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/APIEnvironmentSFOrgID__mdt/fields/OrgID__c.field-meta.xml
<CustomField>
    <fullName>OrgID__c</fullName>
    <description>SF Org id</description>
    <label>OrgID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/classes/Utilities.cls
public without sharing class Utilities {
    public static API_Endpoint__mdt getEndpointConfig(String serviceName) {
        // Get environment Organization id
        String orgId = UserInfo.getOrganizationId(); 
        
        // Get appropriate environment name from custom metadata table
        APIEnvironmentSFOrgID__mdt envt = new APIEnvironmentSFOrgID__mdt();
        API_Endpoint__mdt output = new API_Endpoint__mdt();
        
        envt = [Select Environment__c From APIEnvironmentSFOrgID__mdt Where OrgId__c =: orgId Limit 1];
        output = [Select Id, Client_Id__c, Client_Secret__c, Service_Method__c, Timeout__c, Method__c, Mock_Response_Static_Resource__c, ContentType__c, Type__c, SOAP_Method__c, isOIDCSecured__c, Named_Credential__c from  API_Endpoint__mdt where MasterLabel =:envt.Environment__c AND ServiceName__c =:serviceName and is_Active__c=true limit 1];
    
        return output;
    }

    public static String getBearerToken() {
        String strJWToken = (String)Cache.Org.get('local.sales.JWAToken');
        //System.debug('## Check Token Value:-'+strJWToken);       
        if(String.isNotEmpty(strJWToken)) {
            System.debug('## No need to fetch the token.'); 
            return strJWToken;
        }
        else {     
           
            strJWToken = OIDCAuthorizeService.getBearerToken().jwToken;
             
            if(Test.isRunningTest()) {
                strJWToken = '123456789';
            }
            // System.debug('@@ Partitiona Name:- '+Cache.Org.getName() +' - '+ Cache.Org.getPartition(Cache.Org.getName()));
            Cache.Org.put('local.sales.JWAToken', strJWToken, 1500, Cache.Visibility.ALL, false);
            // System.debug('@@ Cache: - '+Cache.Org.get('local.sales.JWAToken'));       
            return strJWToken;
        } 
    }

    public static String formatPhone(String strPhone) {
        string nonDigits = '[^0-9]';
        string phoneDigits = '';

        // remove all non numeric
        if(strPhone != null && strPhone != ''){
            phoneDigits = strPhone.replaceAll(nonDigits,'');

            // 10 digit: reformat
            if (phoneDigits != null && phoneDigits.length() == 10){
                return '(' + phoneDigits.substring(0,3) + ') ' + phoneDigits.substring(3,6) + '-' + phoneDigits.substring(6,10);
            }
            // 11 digit: if starts with 1, format as 10 digit
            if (phoneDigits != null && phoneDigits.length() == 11) {
                if (phoneDigits.substring(0,1) == '1') {
                    return  '(' + phoneDigits.substring(1,4) + ') ' + phoneDigits.substring(4,7) + '-' + phoneDigits.substring(7,11);
                }
            }
        }

        // if it isn't a 10 or 11 digit number, return the original because
        // it may contain an extension or special information
        return(strPhone);
    }

    /**
     * This method removes all formatting from the phone number that is passed into the method
     */
    public static String removeAllPhoneFormatting(String phoneNumber) {
        return phoneNumber.replace('-','').replace('(','').replace(')','').replace(' ','');
    }

    public static String DateFormatSwitchMMDDYYYTtoYYYYMMDD(String strDate) {   
        String strDateToReturn = null;
            
        if(strDate != null) {
            if(strDate.countMatches('/')==2) {
                String[] strDateSplit = strDate.split('/');
                
                if((strDateSplit[0].length() > 0) && (strDateSplit[0].length() <= 2) && (strDateSplit[1].length() > 0) && (strDateSplit[1].length() <= 2) && (strDateSplit[2].length() == 4)) {
                    strDateToReturn = '';
                    
                    // Year
                    strDateToReturn +=strDateSplit[2] + '-';
                    
                    // Month
                    if(strDateSplit[0].length()==1) {
                        strDateToReturn += '0';
                    }
                    strDateToReturn +=strDateSplit[0] + '-';
                    
                    // Day
                    if(strDateSplit[1].length()==1) {
                        strDateToReturn += '0';
                    }
                    strDateToReturn +=strDateSplit[1];
                }
            } else if(strDate.countMatches('-') == 2) {
                strDateToReturn = strDate;
            }
        }
        return strDateToReturn;     
    }
}