d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/API_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>Store the rest/soap api endpoint information like method,URL,named credentials, timeout etc</description>
    <label>API Endpoint</label>
    <pluralLabel>API Endpoints</pluralLabel>
</CustomObject>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>Client id</description>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>application/json</fullName>
                <default>true</default>
                <label>application/json</label>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>text/xml; charset=utf-8</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>Which named credential to use</description>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Service_Method__c.field-meta.xml
<CustomField>
    <fullName>Service_Method__c</fullName>
    <label>Service Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>ServiceName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/APIEnvironmentSFOrgID__mdt/APIEnvironmentSFOrgID__mdt.object-meta.xml
<CustomObject>
    <description>Used to manage the SF org to connect to dev/demo/e01/prod environments.</description>
    <label>API Environment SF Org ID</label>
    <pluralLabel>API Environment SF Org IDs</pluralLabel>
</CustomObject>

d2c-org/d2c-core/base-code/main/default/objects/APIEnvironmentSFOrgID__mdt/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <description>Dev/demo/e01/prod</description>
    <label>Environment</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/APIEnvironmentSFOrgID__mdt/fields/OrgID__c.field-meta.xml
<CustomField>
    <fullName>OrgID__c</fullName>
    <description>SF Org id</description>
    <label>OrgID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/NonSearchableNumber__mdt/NonSearchableNumber__mdt.object-meta.xml
<CustomObject>
    <label>NonSearchableNumber</label>
    <pluralLabel>NonSearchableNumbers</pluralLabel>
</CustomObject>

d2c-org/d2c-core/base-code/main/default/objects/NonSearchableNumber__mdt/fields/ExcludedNumber__c.field-meta.xml
<CustomField>
    <fullName>ExcludedNumber__c</fullName>
    <label>ExcludedNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/classes/MockMetadataUtils.cls
public class MockMetadataUtils {
    
    public static List<APIEnvironmentSFOrgID__mdt> apiEvts = new List<APIEnvironmentSFOrgID__mdt>();
    public static List<API_Endpoint__mdt> apiEndPts = new List<API_Endpoint__mdt>();
    public static List<NonSearchableNumber__mdt> excludedNums = new List<NonSearchableNumber__mdt>();

    @TestVisible
    public static void insert_custom_metadata_mock(){
	
        APIEnvironmentSFOrgID__mdt apiEvt = new APIEnvironmentSFOrgID__mdt();
        Map<String,Object> fields = (Map<String, Object>) 
            JSON.deserializeUntyped(JSON.serializePretty(apiEvt));
        fields.put(
            APIEnvironmentSFOrgID__mdt.Environment__c.getDescribe().getName(),
            'Dev'
        );
        fields.put(
            APIEnvironmentSFOrgID__mdt.OrgId__c.getDescribe().getName(),
            UserInfo.getOrganizationId()
        );
        apiEvt = (APIEnvironmentSFOrgID__mdt) 
            JSON.deserialize(JSON.serialize(fields), APIEnvironmentSFOrgID__mdt.class);
        
        API_Endpoint__mdt apiEnd = new API_Endpoint__mdt();
        Map<String,Object> fields2 = (Map<String, Object>) 
            JSON.deserializeUntyped(JSON.serializePretty(apiEnd));
        fields2.put(
            API_Endpoint__mdt.MasterLabel.getDescribe().getName(),
            'Dev'
        );
        fields2.put(
            API_Endpoint__mdt.Client_Id__c.getDescribe().getName(),
            '123456789'
        );
          fields2.put(
            API_Endpoint__mdt.Client_Secret__c.getDescribe().getName(),
            'Secret'
        );
        
        fields2.put(
            API_Endpoint__mdt.Service_Method__c.getDescribe().getName(),
            'CPS_Search'
        );
        fields2.put(
            API_Endpoint__mdt.ServiceName__c.getDescribe().getName(),
            'CPS_Search'
        );
        fields2.put(
            API_Endpoint__mdt.Named_Credential__c.getDescribe().getName(),
            'endpoint'
        );
         fields2.put(
            API_Endpoint__mdt.Timeout__c.getDescribe().getName(),
            '3'
        );
        fields2.put(
            API_Endpoint__mdt.Method__c.getDescribe().getName(),
            'CPS_Search'
        );
        fields2.put(
            API_Endpoint__mdt.ContentType__c.getDescribe().getName(),
            'application/json'
        );
        
         apiEnd = (API_Endpoint__mdt) 
            JSON.deserialize(JSON.serialize(fields2), API_Endpoint__mdt.class);
        
        NonSearchableNumber__mdt excludedNum = new NonSearchableNumber__mdt();
        Map<String,Object> fields3 = (Map<String, Object>) 
            JSON.deserializeUntyped(JSON.serializePretty(excludedNum));
        fields3.put(
            NonSearchableNumber__mdt.DeveloperName.getDescribe().getName(),
            'X1231231234'
        );

        fields3.put(
            NonSearchableNumber__mdt.MasterLabel.getDescribe().getName(),
            '1231231234'
        );

        fields3.put(
            NonSearchableNumber__mdt.ExcludedNumber__c.getDescribe().getName(),
            '1231231234'
        );

        excludedNum = (NonSearchableNumber__mdt) 
            JSON.deserialize(JSON.serialize(fields3), NonSearchableNumber__mdt.class);
        
        MockMetadataUtils.apiEvts.add(apiEvt);
        MockMetadataUtils.apiEndPts.add(apiEnd);
        MockMetadataUtils.excludedNums.add(excludedNum);
        
    }
}