d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/API_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>Store the rest/soap api endpoint information like method,URL,named credentials, timeout etc</description>
    <label>API Endpoint</label>
    <pluralLabel>API Endpoints</pluralLabel>
</CustomObject>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>Client id</description>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>application/json</fullName>
                <default>true</default>
                <label>application/json</label>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>text/xml; charset=utf-8</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/isOIDCSecured__c.field-meta.xml
<CustomField>
    <fullName>isOIDCSecured__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field tells whether endpoints are OIDC secured and need JWT for authentication</description>
    <label>is OIDC Secured</label>
    <type>Checkbox</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Mock_Response_Static_Resource__c.field-meta.xml
<CustomField>
    <fullName>Mock_Response_Static_Resource__c</fullName>
    <label>Mock Response Static Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>Which named credential to use</description>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Service_Method__c.field-meta.xml
<CustomField>
    <fullName>Service_Method__c</fullName>
    <label>Service Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/SOAP_Method__c.field-meta.xml
<CustomField>
    <fullName>SOAP_Method__c</fullName>
    <label>SOAP Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
                <default>true</default>
                <label>REST</label>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/classes/HttpHelper.cls
public with sharing class HttpHelper {
    public static HTTPResponse sendAPICRequest(String endPointKey, String requestString) {
        API_Endpoint__mdt endpoint = Utilities.getEndpointConfig(endPointKey);
		String URI = '';
		
		if((endpoint.Named_Credential__c != null) && (endpoint.Named_Credential__c != '')) {
			URI += 'callout:' + endpoint.Named_Credential__c;
		}

		URI += endpoint.Service_Method__c+endpoint.Client_Id__c;

        HttpRequest httpRequestObject = new HttpRequest();
        httpRequestObject.setTimeout(Integer.valueOf(endpoint.Timeout__c));
        httpRequestObject.setMethod(endpoint.Method__c);
		httpRequestObject.setHeader('Content-Type', endpoint.ContentType__c);
		
		if(endpoint.isOIDCSecured__c) {
			httpRequestObject.setHeader('Authorization', 'Bearer '+ Utilities.getBearerToken());
		}
        
        if((requestString != null) && (requestString != '')){
            if(endpoint.Method__c == 'GET') {
                URI += '&' + requestString;
            } else {
                httpRequestObject.setBody(requestString);
            }
        }
        
        httpRequestObject.setEndpoint(URI);
        
        if(endpoint.Type__c == 'SOAP') {
            httpRequestObject.setHeader('SOAPAction', endpoint.SOAP_Method__c);
        }
        
        return new System.Http().send(httpRequestObject);
    }

    /**
     * This method overrides the previous sendAPICRequest, and is used for newer GET requests
     * Use sendAPICRequest(String endPointKey, String requestString) for POST requests
     * For this method the API Endpoint metadata records must include the index values that you passing through the parameterValues
     * Example: 
     * Service Method = /personid/{0} 
     * parmeterValues = {'123456'}
     * URI = /personid/123456
     * @param endPointKey -- Name of the service that you are requestion data from. This should be the value on the ServiceName on API Enpoint records
     * @param parameterValues -- Values of the indexes that you want to replace within the URI
     */
    public static HTTPResponse sendAPICRequest(String endPointKey, String[] parameterValues) {
        API_Endpoint__mdt endpoint = Utilities.getEndpointConfig(endPointKey);
		String URI = '';
		
		if((endpoint.Named_Credential__c != null) && (endpoint.Named_Credential__c != '')) {
			URI += 'callout:' + endpoint.Named_Credential__c;
		}

		URI += endpoint.Service_Method__c+endpoint.Client_Id__c;

        HttpRequest httpRequestObject = new HttpRequest();
        httpRequestObject.setTimeout(Integer.valueOf(endpoint.Timeout__c));
        httpRequestObject.setMethod(endpoint.Method__c);
		httpRequestObject.setHeader('Content-Type', endpoint.ContentType__c);
		
		if(endpoint.isOIDCSecured__c) {
			httpRequestObject.setHeader('Authorization', 'Bearer '+ Utilities.getBearerToken());
		}
        
        URI = String.format(URI, parameterValues);  
        httpRequestObject.setEndpoint(URI);
        
        if(endpoint.Type__c == 'SOAP') {
            httpRequestObject.setHeader('SOAPAction', endpoint.SOAP_Method__c);
        }
        
        return new System.Http().send(httpRequestObject);
    }
    
    public static Boolean setMockCalloutIfTest(API_Endpoint__mdt endpoint) {
        return setMockCalloutIfTest(endpoint,200,endpoint.Mock_Response_Static_Resource__c);
    }
    
    public static Boolean setMockCalloutIfTest(API_Endpoint__mdt endpoint, Integer httpStatusCode, String mockResponseStaticResource) {
        Boolean isMockCallSet = false;

        if (Test.isRunningTest()) {
            StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
            mock.setStaticResource(mockResponseStaticResource);
            mock.setStatusCode(httpStatusCode);
            mock.setHeader('Content-Type', endpoint.ContentType__c);
            Test.setMock(HttpCalloutMock.class, mock); //  Setup to call mock web service when method called from test 
            isMockCallSet = true;
        }

        return isMockCallSet;
    }
}