d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/API_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>Store the rest/soap api endpoint information like method,URL,named credentials, timeout etc</description>
    <label>API Endpoint</label>
    <pluralLabel>API Endpoints</pluralLabel>
</CustomObject>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>Client id</description>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>application/json</fullName>
                <default>true</default>
                <label>application/json</label>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>text/xml; charset=utf-8</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>Which named credential to use</description>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Service_Method__c.field-meta.xml
<CustomField>
    <fullName>Service_Method__c</fullName>
    <label>Service Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>ServiceName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/APIEnvironmentSFOrgID__mdt/APIEnvironmentSFOrgID__mdt.object-meta.xml
<CustomObject>
    <description>Used to manage the SF org to connect to dev/demo/e01/prod environments.</description>
    <label>API Environment SF Org ID</label>
    <pluralLabel>API Environment SF Org IDs</pluralLabel>
</CustomObject>

d2c-org/d2c-core/base-code/main/default/objects/APIEnvironmentSFOrgID__mdt/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <description>Dev/demo/e01/prod</description>
    <label>Environment</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/APIEnvironmentSFOrgID__mdt/fields/OrgID__c.field-meta.xml
<CustomField>
    <fullName>OrgID__c</fullName>
    <description>SF Org id</description>
    <label>OrgID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/classes/tstOIDCAuthservice.cls
@isTest
public with sharing class tstOIDCAuthservice {
    static testMethod void testGetBearerToken() {				
		StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('MockOidcGetBearerToken');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock); 
        MockMetadataUtils.insert_custom_metadata_mock();
		APIEnvironmentSFOrgID__mdt apiEvt = new APIEnvironmentSFOrgID__mdt();
		apiEvt.Environment__c='Dev';
		OrgId__c=        UserInfo.getOrganizationId();   
		insert apiEvt;
		API_Endpoint__mdt apiEnd = new API_Endpoint__mdt();
		apiEnd.MasterLabel= 'Dev';
        apiEnd.Client_Id__c=    '123456789';
        apiEnd.Client_Secret__c='Secret';
        apiEnd.Service_Method__c='OIDCAuthorizeAPI';
        apiEnd.ServiceName__c='OIDCAuthorizeAPI';
        apiEnd.Named_Credential__c='endpoint';
        apiEnd.Timeout__c='3';
        apiEnd.Method__c='CPS_Search';
        apiEnd.ContentType__c=  'application/json';
        insert apiEnd;
        OIDCAuthorizeService.getBearerToken();		
	}
}