d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/API_Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>Store the rest/soap api endpoint information like method,URL,named credentials, timeout etc</description>
    <label>API Endpoint</label>
    <pluralLabel>API Endpoints</pluralLabel>
</CustomObject>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>Client id</description>
    <label>Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>application/json</fullName>
                <default>true</default>
                <label>application/json</label>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>text/xml; charset=utf-8</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>Which named credential to use</description>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Service_Method__c.field-meta.xml
<CustomField>
    <fullName>Service_Method__c</fullName>
    <label>Service Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/objects/API_Endpoint__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/d2c-core/base-code/main/default/classes/OIDCAuthorizeService.cls
public with sharing class OIDCAuthorizeService {
    public final static string ENDPOINT_OIDC_AUTHORIZE = 'OIDCAuthorizeAPI';
    public static OIDCAuthorizeResponse getBearerToken() {
        API_Endpoint__mdt endPoint= Utilities.getEndPointConfig(ENDPOINT_OIDC_AUTHORIZE);
        Http http = new Http();
        HttpRequest httpReq = new HttpRequest();
        String strTokenType;
        Integer expiresIn;  
        // Form the request for callout to OIDC Webservice
        httpReq.setHeader('Content-Type', endPoint.ContentType__c);

        if((endpoint.Named_Credential__c != null) && (endpoint.Named_Credential__c != '')) {
            httpReq.setEndpoint('callout:'+endpoint.Named_Credential__c+endPoint.Service_Method__c);
        }
        else{
            httpReq.setEndpoint('callout:APIConnectOIDCNamedCredential'+endPoint.Service_Method__c);
        }
        httpReq.setTimeout(Integer.valueOf(endPoint.Timeout__c));
        httpReq.setMethod(endpoint.Method__c);
        //httpReq.setHeader('X-IBM-Client-Secret', endPoint.Client_Secret__c); 
        httpReq.setHeader('X-IBM-Client-Id', endPoint.Client_Id__c); 
        String username = '{!$Credential.UserName}';
        String password = '{!$Credential.Password}';
        httpReq.setBody('grant_type=password&scope=openid+profile+address+email&username='+username+'&password='+password);
        //System.debug('@@ Request Body:-'+httpReq.getBody());
        // Make the webservice call and store the response
        HttpResponse httpResp = new Http().send(httpReq);
        return new OIDCAuthorizeResponse(httpResp);
    }
    public class OIDCAuthorizeResponse{
       @AuraEnabled public String jwToken;
       @AuraEnabled public String tokenType;
       @AuraEnabled public Integer expiresIn;
        public OIDCAuthorizeResponse(HttpResponse response){
            // Parse the response to get the access token
            System.JSONParser parser = JSON.createParser(response.getBody());
            while (parser.nextToken() != null) {
                if(parser.getCurrentToken()== JSONToken.FIELD_NAME){
                    String fieldName = parser.getText();
                    parser.nextToken();
                    if(fieldName == 'access_token'){
                        this.JWToken = parser.getText();
                    } else if(fieldName == 'expires_in') {
                        this.expiresIn = parser.getIntegerValue(); 
                    } else if(fieldName == 'token_type') {
                        this.tokenType = parser.getText();  
                    }
                }
            }
        }
        
    }
}