d2c-org/d2c-core/base-configurations/main/default/objects/Account/recordTypes/Affiliation.recordType-meta.xml
<RecordType>
    <fullName>Affiliation</fullName>
    <active>true</active>
    <description>A credit union or other affiliation with the consumer.</description>
    <label>Affiliation</label>
</RecordType>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ILH: The credit union or other association the consumer is associated to for the opportunity.</description>
    <label>Affiliation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Affiliation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliation Opportunities</relationshipLabel>
    <relationshipName>AffiliationOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/HealthAssessment__c.field-meta.xml
<CustomField>
    <fullName>HealthAssessment__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Health concerns that may prevent customer from qualifying for a traditional, underwritten life insurance policy. This is a requirement for the needs assessment.</description>
    <inlineHelpText>Are you aware of any medical issues or health concerns that you think would keep you from qualifying for a traditional, underwritten life insurance policy?</inlineHelpText>
    <label>Health Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Health Issues</fullName>
            </value>
            <value>
                <fullName>No Health Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/InsurancePurpose__c.field-meta.xml
<CustomField>
    <fullName>InsurancePurpose__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Need or purpose for the insurance coverage, such as funeral expenses or income replacement. This is a requirement for the needs assessment.</description>
    <label>Insurance Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Final Expenses</fullName>
            </value>
            <value>
                <fullName>Income Replacement</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Undecided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product, product family, or type of insurance based on primary campaign source.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/TobaccoUse__c.field-meta.xml
<CustomField>
    <fullName>TobaccoUse__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Indicates if the consumer uses tobacco, which is utilized for particular product underwriting.</description>
    <label>Tobacco Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>Age based on todays date. If deceased, the age at death.</description>
    <label>Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/BillingMethod__c.field-meta.xml
<CustomField>
    <fullName>BillingMethod__c</fullName>
    <description>Billing method - from Eligible Billing Options in product info response</description>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Billing Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/CoverageAmount__c.field-meta.xml
<CustomField>
    <fullName>CoverageAmount__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Coverage Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>Gender required by actuaries for insurance premiums.</description>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/HealthAssessment__c.field-meta.xml
<CustomField>
    <fullName>HealthAssessment__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>Health concerns that may prevent customer from qualifying for a traditional, underwritten life insurance policy.</description>
    <inlineHelpText>Are you aware of any medical issues or health concerns that you think would keep you from qualifying for a traditional, underwritten life insurance policy?</inlineHelpText>
    <label>Health Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Health Issues</fullName>
            </value>
            <value>
                <fullName>No Health Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/InsurancePurpose__c.field-meta.xml
<CustomField>
    <fullName>InsurancePurpose__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Insurance Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Final Expenses</fullName>
            </value>
            <value>
                <fullName>Income Replacement</fullName>
            </value>
            <value>
                <fullName>Gift</fullName>
            </value>
            <value>
                <fullName>Undecided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/PaperKitRequestDate__c.field-meta.xml
<CustomField>
    <fullName>PaperKitRequestDate__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>Date the action was taken in the cart</description>
    <label>Paper Kit Request Date</label>
    <type>Date</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/PaymentFrequency__c.field-meta.xml
<CustomField>
    <fullName>PaymentFrequency__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Payment Frequency</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/ResidentState__c.field-meta.xml
<CustomField>
    <fullName>ResidentState__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Resident State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/TobaccoUse__c.field-meta.xml
<CustomField>
    <fullName>TobaccoUse__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Tobacco Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-objects/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>WI</fullName>
    </customValue>
    <description>Abbreviated States  Includes PR,VI,FM,GU</description>
    <masterLabel>States</masterLabel>
</GlobalValueSet>

d2c-org/ilh-sales/rate-page/main/default/classes/ILHQuoteHelperTests.cls
/**
 * Copyright: TruStage
 * Purpose: Unit tests for the ILHQuoteHelper class
 */
@isTest
private class ILHQuoteHelperTests {

    @testSetup static void setup() {
        Account personAccount = new Account (
            PersonBirthdate = Date.today(),
            FirstName = 'Test',
            LastName = 'Test',
            Gender__pc = 'Male',
            PersonMailingState = 'WI',
            PersonHomePhone = '1111111111',
            ShippingCity = 'Madison',
            ShippingCountry = 'US',
            ShippingPostalCode = '11111',
            ShippingState = 'WI',
            ShippingStreet = '123 Main Street',
            PersonEmail = 'test@test.com',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId()
        );
        insert personAccount;

        Account affiliation = new Account (
            Name = 'Test',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Affiliation').getRecordTypeId()
        );
        insert affiliation;

        Opportunity newOpp = new Opportunity(
            Name = 'TestOpp',
            StageName = 'Quote',
            CloseDate = Date.today(),
            Affiliation__c = affiliation.id,
            AccountId = personAccount.id,
            HealthAssessment__c = 'No Health Issues',
            InsurancePurpose__c = 'Final Expenses',
            TobaccoUse__c = 'No'
        );
        insert newOpp;

        Product2 newProduct = new Product2(
            ProductCode = 'TestProd',
            Name = 'TestProd',
            IsActive = true
        );
        insert newProduct;  
    }

    @isTest
    static void getQuotesTest() {
        ILHQuoteHelper helper = new ILHQuoteHelper();
        Map<String, Object> payload = new Map<String, Object>();

        Id oppId = [SELECT id FROM Opportunity WHERE Name =: 'TestOpp' LIMIT 1].id;
        payload.put('oppId', oppId);
        payload.put('productCode', 'TestProd');
        helper.insertQuote(payload);
        Test.startTest();
        List<ILHQuoteHelper.ResultsWrapper> results = helper.getQuotes(oppId);
        Assert.areEqual(1, results.size());
    }

    @isTest
    static void insertUpdateQuoteTest() {
        ILHQuoteHelper helper = new ILHQuoteHelper();
        Product2 product = [SELECT id FROM Product2 WHERE ProductCode =: 'TestProd'];
        Opportunity opp = [SELECT id, AccountId, Affiliation__c, HealthAssessment__c, InsurancePurpose__c, TobaccoUse__c, Account.Age__pc, Account.PersonBirthdate, 
                            Account.Gender__pc, Account.PersonMailingState, Account.PersonHomePhone, Account.ShippingCity, Account.ShippingCountry, 
                            Account.ShippingPostalCode, Account.ShippingState, Account.ShippingStreet, Account.PersonEmail FROM Opportunity WHERE Name =: 'TestOpp' LIMIT 1];
        Test.startTest();
        Map<String, Object> payload = new Map<String, Object>();
        payload.put('oppId', opp.id);
        payload.put('cost', '4.50');
        payload.put('coverage', '3000');
        payload.put('productCode', 'TestProd');
        payload.put('decision', 'Email Summary');
        payload.put('paymentFrequency', 'Monthly');
        payload.put('billingMethod', 'ACH');

        helper.insertQuote(payload);
        Quote q = [SELECT id, Affiliation__c, Age__c, Birthdate__c, Gender__c, HealthAssessment__c, InsurancePurpose__c, TobaccoUse__c, ResidentState__c, Phone, ShippingCity,
                    ShippingCountry, ShippingPostalCode, ShippingState, ShippingStreet, Product__c, CoverageAmount__c, Premium__c, Status, Email, BillingMethod__c,  PaymentFrequency__c
                    FROM Quote WHERE OpportunityId =: opp.id];

        Assert.isNotNull(q);
        Assert.areEqual(opp.Affiliation__c, q.Affiliation__c);
        Assert.areEqual(opp.Account.Age__pc, q.Age__c);
        Assert.areEqual(opp.Account.PersonBirthdate, q.Birthdate__c);
        Assert.areEqual(opp.Account.Gender__pc, q.Gender__c);
        Assert.areEqual(opp.HealthAssessment__c, q.HealthAssessment__c);
        Assert.areEqual(opp.InsurancePurpose__c, q.InsurancePurpose__c);
        Assert.areEqual(opp.TobaccoUse__c, q.TobaccoUse__c);
        Assert.areEqual(opp.Account.PersonMailingState, q.ResidentState__c);
        Assert.areEqual(opp.Account.PersonHomePhone, q.Phone);
        Assert.areEqual(opp.Account.ShippingCountry, q.ShippingCountry);
        Assert.areEqual(opp.Account.ShippingPostalCode, q.ShippingPostalCode);
        Assert.areEqual(opp.Account.ShippingState, q.ShippingState);
        Assert.areEqual(opp.Account.ShippingStreet, q.ShippingStreet);
        Assert.areEqual(Integer.valueOf((String)payload.get('coverage')), q.CoverageAmount__c);
        Assert.areEqual(Decimal.valueOf((String)payload.get('cost')), q.Premium__c);
        Assert.areEqual(product.id, q.Product__c);
        Assert.areEqual(opp.Account.PersonEmail, q.Email);
        Assert.areEqual(payload.get('billingMethod'), q.BillingMethod__c);
        Assert.areEqual(payload.get('paymentFrequency'), q.PaymentFrequency__c);

        payload.put('decision', 'Paper Kit');
        payload.put('coverage', '4000');
        payload.put('quoteId', q.id);
        helper.updateQuote(payload);
        q = [SELECT Status, CoverageAmount__c, PaperKitRequestDate__c FROM Quote WHERE OpportunityId =: opp.id];
        Assert.areEqual('Paper Kit', q.Status);
        Assert.areEqual(Date.today(), q.PaperKitRequestDate__c);
        Assert.areEqual(3000, q.CoverageAmount__c, 'Coverage hasn\'t changed');

        //Updating email on person accout
        Account acc = new Account (
            id = opp.AccountId,
            PersonEmail = 'test2@test.com'
        );
        update acc;

        payload.put('decision', 'Email Summary');
        helper.updateQuote(payload);
        q = [SELECT Email FROM Quote WHERE OpportunityId =: opp.id];
        Assert.areEqual(opp.Account.PersonEmail, q.Email, 'Email should be equal to original email, not the updated one');

        try {
            payload = new Map<String, Object>();
            payload.put('oppId', '1');
            helper.insertQuote(payload);
            Assert.fail();
        } catch (Exception ex) {}

        try {
            payload = new Map<String, Object>();
            payload.put('quoteId', '1');
            helper.updateQuote(payload);
            Assert.fail();
        } catch (Exception ex) {}
    }

    @isTest
    static void deleteQuoteTest() {
        ILHQuoteHelper helper = new ILHQuoteHelper();
        Id oppId = [SELECT id FROM Opportunity WHERE Name =: 'TestOpp' LIMIT 1].id;

        Map<String, Object> payload = new Map<String, Object>();
        payload.put('oppId', oppId);
        payload.put('productCode', 'TestProd');
        helper.insertQuote(payload);

        List<ILHQuoteHelper.ResultsWrapper> results = helper.getQuotes(oppId);
        helper.deleteQuote(results[0].quoteId);
        results = helper.getQuotes(oppId);
        Assert.areEqual(0, results.size());
    }
}