d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Error log for tracking platform errors.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Err-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/CurrentUser__c.field-meta.xml
<CustomField>
    <fullName>CurrentUser__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that triggered the error.</description>
    <inlineHelpText>User that triggered the error.</inlineHelpText>
    <label>Current User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/ErrorDescription__c.field-meta.xml
<CustomField>
    <fullName>ErrorDescription__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Detailed description of error.</description>
    <inlineHelpText>Detailed description of error.</inlineHelpText>
    <label>Error Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Type of operation that was preformed when the error occurred.</description>
    <inlineHelpText>Type of operation that was preformed when the error occurred.</inlineHelpText>
    <label>Operation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Indicates where the error originated.</description>
    <inlineHelpText>Indicates where the error originated.</inlineHelpText>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Id of record that triggered the error.</description>
    <inlineHelpText>Id of record that triggered the error.</inlineHelpText>
    <label>Reference Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/RequestData__c.field-meta.xml
<CustomField>
    <fullName>RequestData__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Data that was entered by user when the error occurred.</description>
    <inlineHelpText>Data that was entered by user when the error occurred.</inlineHelpText>
    <label>Request Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Name of the service that was called when the error occurred.</description>
    <inlineHelpText>Name of the service that was called when the error occurred.</inlineHelpText>
    <label>Service Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>The stack trace of a thrown exception</description>
    <inlineHelpText>The stack trace of a thrown exception</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/TypeOfError__c.field-meta.xml
<CustomField>
    <fullName>TypeOfError__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Describes the error type.</description>
    <inlineHelpText>Describes the error type.</inlineHelpText>
    <label>Type Of Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/ExceptionLog__e.object-meta.xml
<CustomObject>
    <description>Error log for tracking platform errors.</description>
    <label>Exception Log</label>
    <pluralLabel>Exception Logs</pluralLabel>
</CustomObject>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/CurrentUser__c.field-meta.xml
<CustomField>
    <fullName>CurrentUser__c</fullName>
    <description>Id of user that triggered the error.</description>
    <inlineHelpText>Id of user that triggered the error.</inlineHelpText>
    <label>Current User</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ErrorDescription__c.field-meta.xml
<CustomField>
    <fullName>ErrorDescription__c</fullName>
    <description>Detailed description of error.</description>
    <inlineHelpText>Detailed description of error.</inlineHelpText>
    <label>Error Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Type of operation that was preformed when the error occurred.</description>
    <label>Operation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <description>Indicates where the error originated.</description>
    <inlineHelpText>Indicates where the error originated.</inlineHelpText>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <description>Id of record that triggered the error.</description>
    <inlineHelpText>Id of record that triggered the error.</inlineHelpText>
    <label>Reference Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/RequestData__c.field-meta.xml
<CustomField>
    <fullName>RequestData__c</fullName>
    <description>Data that was entered by user when the error occurred.</description>
    <label>Request Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <description>Name of the service that was called when the error occurred.</description>
    <label>Service Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>The stack trace of a thrown exception</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/TypeOfError__c.field-meta.xml
<CustomField>
    <fullName>TypeOfError__c</fullName>
    <description>Describes the error type.</description>
    <label>Type Of Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/classes/ErrorLogEventHelperTests.cls
@isTest
public with sharing class ErrorLogEventHelperTests {
    
    @isTest
    static void addErrorToLogTest() {
        ExceptionLog__e logRecord = new ExceptionLog__e();
			
		logRecord.ErrorDescription__c = 'Test Description';
		logRecord.ProcessName__c = 'ErrorLogEventHelperTests';
		logRecord.ReferenceID__c = '11111111111111';
		logRecord.CurrentUser__c = UserInfo.getUserId();
		logRecord.Operation__c = 'Inserting Account Records';
		logRecord.RequestData__c = 'Test Request Data';
		logRecord.ServiceName__c = 'Some_Service';
		logRecord.StackTrace__c	= 'Test Stack Trace';
		logRecord.TypeOfError__c = 'Test Type Of Error';

        Test.startTest();
		eventBus.publish(logRecord);
        Test.stopTest();

        ErrorLog__c[] errorLog = [SELECT id, ErrorDescription__c, ProcessName__c, ReferenceID__c, CurrentUser__c, Operation__c, RequestData__c,
                                ServiceName__c, StackTrace__c, TypeOfError__c FROM ErrorLog__c];

        Assert.areEqual(1, errorLog.size(), 'Error log has been inserted');
        Assert.areEqual('Test Description', errorLog[0].ErrorDescription__c, 'Error description has been mapped');
        Assert.areEqual('ErrorLogEventHelperTests', errorLog[0].ProcessName__c, 'Process Name has been mapped');
        Assert.areEqual('11111111111111', errorLog[0].ReferenceID__c, 'Reference Id has been mapped');
        Assert.areEqual(UserInfo.getUserId(), errorLog[0].CurrentUser__c, 'Current User has been mapped');
        Assert.areEqual('Inserting Account Records', errorLog[0].Operation__c, 'Operation has been mapped');
        Assert.areEqual('Test Request Data', errorLog[0].RequestData__c, 'Request Data has been mapped');
        Assert.areEqual('Some_Service', errorLog[0].ServiceName__c, 'Service Name has been mapped');
        Assert.areEqual('Test Stack Trace', errorLog[0].StackTrace__c, 'Stack Trace has been mapped');
        Assert.areEqual('Test Type Of Error', errorLog[0].TypeOfError__c, 'Type Of Error has been mapped');
    }
}