d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <description>Error log for tracking platform errors.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Err-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/CurrentUser__c.field-meta.xml
<CustomField>
    <fullName>CurrentUser__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that triggered the error.</description>
    <inlineHelpText>User that triggered the error.</inlineHelpText>
    <label>Current User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/ErrorDescription__c.field-meta.xml
<CustomField>
    <fullName>ErrorDescription__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Detailed description of error.</description>
    <inlineHelpText>Detailed description of error.</inlineHelpText>
    <label>Error Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Type of operation that was preformed when the error occurred.</description>
    <inlineHelpText>Type of operation that was preformed when the error occurred.</inlineHelpText>
    <label>Operation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Indicates where the error originated.</description>
    <inlineHelpText>Indicates where the error originated.</inlineHelpText>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Id of record that triggered the error.</description>
    <inlineHelpText>Id of record that triggered the error.</inlineHelpText>
    <label>Reference Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/RequestData__c.field-meta.xml
<CustomField>
    <fullName>RequestData__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Data that was entered by user when the error occurred.</description>
    <inlineHelpText>Data that was entered by user when the error occurred.</inlineHelpText>
    <label>Request Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Status from callout.</description>
    <inlineHelpText>Status from callout.</inlineHelpText>
    <label>Response Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Name of the service that was called when the error occurred.</description>
    <inlineHelpText>Name of the service that was called when the error occurred.</inlineHelpText>
    <label>Service Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>The stack trace of a thrown exception</description>
    <inlineHelpText>The stack trace of a thrown exception</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ErrorLog__c/fields/TypeOfError__c.field-meta.xml
<CustomField>
    <fullName>TypeOfError__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Describes the error type.</description>
    <inlineHelpText>Describes the error type.</inlineHelpText>
    <label>Type Of Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/ExceptionLog__e.object-meta.xml
<CustomObject>
    <description>Error log for tracking platform errors.</description>
    <label>Exception Log</label>
    <pluralLabel>Exception Logs</pluralLabel>
</CustomObject>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/CurrentUser__c.field-meta.xml
<CustomField>
    <fullName>CurrentUser__c</fullName>
    <description>Id of user that triggered the error.</description>
    <inlineHelpText>Id of user that triggered the error.</inlineHelpText>
    <label>Current User</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ErrorDescription__c.field-meta.xml
<CustomField>
    <fullName>ErrorDescription__c</fullName>
    <description>Detailed description of error.</description>
    <inlineHelpText>Detailed description of error.</inlineHelpText>
    <label>Error Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>Type of operation that was preformed when the error occurred.</description>
    <label>Operation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <description>Indicates where the error originated.</description>
    <inlineHelpText>Indicates where the error originated.</inlineHelpText>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <description>Id of record that triggered the error.</description>
    <inlineHelpText>Id of record that triggered the error.</inlineHelpText>
    <label>Reference Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/RequestData__c.field-meta.xml
<CustomField>
    <fullName>RequestData__c</fullName>
    <description>Data that was entered by user when the error occurred.</description>
    <label>Request Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ResponseCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseCode__c</fullName>
    <description>Status from callout.</description>
    <label>Response Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <description>Name of the service that was called when the error occurred.</description>
    <label>Service Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>The stack trace of a thrown exception</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/objects/ExceptionLog__e/fields/TypeOfError__c.field-meta.xml
<CustomField>
    <fullName>TypeOfError__c</fullName>
    <description>Describes the error type.</description>
    <label>Type Of Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/error-handling-framework/main/default/classes/ErrorLogEventHelper.cls
/**
************************************************************************
Apex Class Name    : ErrorLogEventHelper
Created Date       : September 26, 2023
@description       : This class is helper class for the ErrorLogTrigger
@author            : Adam Perschke-Ely
Modification Log:
Ver   Date         Author                               Modification
1.0   09-26-2023   Adam Perschke-Ely                   Initial Version
************************************************************************
*/
public with sharing class ErrorLogEventHelper {
    /**
    ***********************************************************************************************
    @Method Name    : addErrorToLog
    @author         : Adam Perschke-Ely
    @description    : This method maps exception log to error log object, then inserts the records
    @param errors   : List of Exception Logs from ErrorLogTrigger
    ***********************************************************************************************
    */
    public static void addErrorToLog(List<ExceptionLog__e> errors) {
        List<ErrorLog__c> logs = new List<ErrorLog__c>();
        for(ExceptionLog__e error : errors) {
            //Map Exception log to Error Log custom object
            ErrorLog__c logRecord = new ErrorLog__c();
            logRecord.ErrorDescription__c = error.ErrorDescription__c;
            logRecord.ProcessName__c = error.ProcessName__c;
            logRecord.ReferenceID__c = error.ReferenceID__c;
            logRecord.CurrentUser__c = error.CurrentUser__c;
            logRecord.Operation__c = error.Operation__c;
            logRecord.RequestData__c = error.RequestData__c;
            logRecord.ServiceName__c = error.ServiceName__c;
            logRecord.StackTrace__c	= error.StackTrace__c;
            logRecord.TypeOfError__c = error.TypeOfError__c;
            logRecord.ResponseCode__c = error.ResponseCode__c;
            logs.add(logRecord);
        }
        
        //If there's any logs, then insert them
        if(!logs?.isEmpty()) {
            insert logs;
        }
    }
}