d2c-org/d2c-core/base-configurations/main/default/objects/Account/fields/ContractNumberFormatted__c.field-meta.xml
<CustomField>
    <fullName>ContractNumberFormatted__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Formatted Contract Number used for display, from Contract Number Unformatted.</description>
    <formula>LEFT(ContractNumberUnformatted__c, 3) + &quot;-&quot; + MID(ContractNumberUnformatted__c,4,4) + &quot;-&quot; + RIGHT(ContractNumberUnformatted__c,1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Number</label>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-configurations/main/default/objects/Account/fields/ContractNumberUnformatted__c.field-meta.xml
<CustomField>
    <fullName>ContractNumberUnformatted__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Sourced from CUIC. Contract number of account.</description>
    <externalId>true</externalId>
    <label>Contract Number Unformatted</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

d2c-org/d2c-core/base-objects/main/default/objects/Account/fields/DomicileState__c.field-meta.xml
<CustomField>
    <fullName>DomicileState__c</fullName>
    <description>Sourced from CUIC. </description>
    <label>Domicile State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ILH: The credit union or other association the consumer is associated to for the opportunity.</description>
    <label>Affiliation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Affiliation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliation Opportunities</relationshipLabel>
    <relationshipName>AffiliationOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/TobaccoUse__c.field-meta.xml
<CustomField>
    <fullName>TobaccoUse__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Indicates if the consumer uses tobacco, which is utilized for particular product underwriting.</description>
    <label>Tobacco Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/d2c-core/base-objects/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <description>Abbreviated States  Includes PR,VI,FM,GU</description>
    <masterLabel>States</masterLabel>
</GlobalValueSet>

d2c-org/ilh-sales/product-list/main/default/classes/ProductListController.cls
public with sharing class ProductListController {
    @AuraEnabled
    public static List<ProductQuoteResult> getEligibleQuotes(Map<String, Object> requestObj) {
      
      String reqString = JSON.serialize(requestObj, true);   
      
      ConsumerEligibleQuoteResponse.QuoteResponse response=new ILHProductQuoteService().getAvailableProducts(requestObj);
      List<ProductQuoteResult> pqrlst = new list<ProductQuoteResult>();
     
      for(ConsumerEligibleQuoteResponse.ProductQuotes pr:response.productQuotes ){
         if(pr.insuranceProductDetails!=null && pr.InsuranceProductDetails.returnFlag){
             pqrlst.add(new ProductQuoteResult(pr));
         }
      }
      pqrlst = ProductListRulesHelper.applyProductRules(pqrlst);
      return pqrlst ;
    }

    @AuraEnabled
    public static Opportunity getOpportunity(String oppoId) {  
      Opportunity opp = new Opportunity();
      try {
         opp = [SELECT Id, Name,TobaccoUse__c, AccountId,Account.ContractNumberUnformatted__c, Account.ContractNumberFormatted__c, Account.PersonMailingState, Account.Gender__pc	,Account.DomicileState__c, Account.BillingPostalCode,  Account.Age__pc,Account.PersonBirthDate, Affiliation__r.ContractNumberUnformatted__c From Opportunity WHERE Id=:oppoId];
      } catch(Exception ex) {
         new ErrorLogger(ex, 'An error occured while getting opportunity.', 'ProductListController.cls', oppoId, 'Get Opportunity', null, null, null);     
      }  
      return opp;
    }

    
}