d2c-org/d2c-core/base-configurations/main/default/objects/Account/fields/ContractNumberUnformatted__c.field-meta.xml
<CustomField>
    <fullName>ContractNumberUnformatted__c</fullName>
    <businessOwnerGroup>ITDataOwner</businessOwnerGroup>
    <description>Sourced from CUIC. Contract number of account.</description>
    <externalId>true</externalId>
    <label>Contract Number Unformatted</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ILH: The credit union or other association the consumer is associated to for the opportunity.</description>
    <label>Affiliation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Affiliation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliation Opportunities</relationshipLabel>
    <relationshipName>AffiliationOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Opportunity/fields/TobaccoUse__c.field-meta.xml
<CustomField>
    <fullName>TobaccoUse__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <description>ILH: Indicates if the consumer uses tobacco, which is utilized for particular product underwriting.</description>
    <label>Tobacco Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Affiliation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

d2c-org/ilh-sales/base-objects/main/default/objects/Quote/fields/TobaccoUse__c.field-meta.xml
<CustomField>
    <fullName>TobaccoUse__c</fullName>
    <businessOwnerGroup>ILHSalesDataOwner</businessOwnerGroup>
    <label>Tobacco Use</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

d2c-org/ilh-sales/base-code/main/default/objects/RateComparisonInterval__mdt/RateComparisonInterval__mdt.object-meta.xml
<CustomObject>
    <description>Interval information for rate page.  Label = Product Category</description>
    <label>Rate Comparison Interval</label>
    <pluralLabel>Rate Comparison Intervals</pluralLabel>
</CustomObject>

d2c-org/ilh-sales/base-code/main/default/objects/RateComparisonInterval__mdt/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <description>Intervals that should be displayed for this product category.</description>
    <inlineHelpText>Intervals that should be displayed for this product category.</inlineHelpText>
    <label>Interval</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/ilh-sales/base-code/main/default/objects/RateComparisonInterval__mdt/fields/LowerBound__c.field-meta.xml
<CustomField>
    <fullName>LowerBound__c</fullName>
    <description>Lower coverage amount for this product category.</description>
    <inlineHelpText>Lower coverage amount for this product category.</inlineHelpText>
    <label>Lower Bound</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/ilh-sales/base-code/main/default/objects/RateComparisonInterval__mdt/fields/UpperBound__c.field-meta.xml
<CustomField>
    <fullName>UpperBound__c</fullName>
    <description>Upper coverage amount for this product category.</description>
    <inlineHelpText>Upper coverage amount for this product category.</inlineHelpText>
    <label>Upper Bound</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

d2c-org/ilh-sales/rate-page/main/default/classes/QuoteServiceHelper.cls
/***
Copyright: TruStage
Purpose: Service class that get eligible product quotes
1.0 - Adam Perschke-Ely   - 1/2/2024  - Created for new D2C Salesfore instance.
***/
public with sharing class QuoteServiceHelper {
    private Map<String, Object> quoteRequestMap;
    private Id oppId;
    /**
     * Purpose: This method get eligible rates from ILHProductQuoteService
     * @param rateRequest : Request to send to ILHProductQuoteService
     * @return : Instance or EligibleProductRateWrapper class
     */
    public EligibleProductRateWrapper getRates(Map<String, Object> requestMap) {
        try {
            String productCategory = (String)requestMap.get('productCategory');
            Map<String, Object> rateRequest = getQuoteRequestMap(requestMap);

            List<EligibleProductQuoteResult> rates = EligibleProductQuoteResult.parse(new ILHProductQuoteService().getAvailableProducts(rateRequest), productCategory);
            EligibleProductRateWrapper wrapper = new EligibleProductRateWrapper(rates);
            return wrapper;
        } catch (Exception ex) {
            new ErrorLogger(ex, ex.getMessage(), 'QuoteServiceHelper.cls', null, 'getRates', null, null, null);
        }
        return null;
    }

    /**
     * Purpose: Creates request map for quote service
     * @param requestMap Request from rate page
     * @return New request map to send to quote service
     */
    @TestVisible 
    private Map<String, Object> getQuoteRequestMap(Map<String, Object> requestMap) {
        string billMethod;

        String frequency = (String)requestMap.get('frequency');
        String billingMethodCode = (String)requestMap.get('billingMethodCode');
        String productCategory = (String)requestMap.get('productCategory');
        oppId = (Id)requestMap.get('oppId');

        RateComparisonInterval__mdt rci = ILHUtilities.getRateComparisonInterval(productCategory);

        quoteRequestMap = new Map<String, Object> {
            'channel' => 'Telem',
            'maxCoverage' => rci.UpperBound__c,
            'minCoverage' => rci.LowerBound__c,
            'coverageInterval' => rci.Interval__c,
            'organizationId' => '',
            'requestingSystemName' => 'sforcecs',
            'asOfDate' => Date.today()
        };

        if (String.isNotBlank(frequency) && String.isNotBlank(billingMethodCode)) {//Billing Method and frequency need to have values in order to send in request
            quoteRequestMap.put('frequency',frequency);  

            if (billingMethodCode.equalsIgnoreCase('ACH/PAC')) {//Consumer Eligible Quote service doesn't accept ACH/PAC
                billingMethodCode = 'ACH';
            }
            quoteRequestMap.put('billingMethod',billingMethodCode);
        }
        mapOpportunityInformation();
        return quoteRequestMap;
    }

    /**
     * Purpose: Maps opportunity information to quote request map
     * @param quoteRequestMap Pass-by-value parameter
     * @param oppId Id of opportunity to query on
     */
    private void mapOpportunityInformation() {
        Opportunity opp = [SELECT TobaccoUse__c, Affiliation__r.ContractNumberUnformatted__c, Account.PersonBirthdate, Account.Age__pc, Account.Gender__pc, 
                            Account.PersonMailingState FROM Opportunity WHERE id =: oppId WITH USER_MODE];
        quoteRequestMap.put('tobaccoUse',opp?.TobaccoUse__c != null ? (opp.TobaccoUse__c == 'No' ? 0 : 1) : null);
        quoteRequestMap.put('gender', opp?.Account?.Gender__pc != null ? (opp.Account.Gender__pc == 'Male' ? 1 : 0) : null);
        quoteRequestMap.put('residentState', opp?.Account?.PersonMailingState != null ? opp.Account.PersonMailingState : '');
        quoteRequestMap.put('issueAge', opp?.Account?.Age__pc != null ? String.valueOf(opp.Account.Age__pc) : '');
        quoteRequestMap.put('contractNumber', opp?.Affiliation__r?.ContractNumberUnformatted__c != null ? opp.Affiliation__r.ContractNumberUnformatted__c : '');
        quoteRequestMap.put('birthDate', opp?.Account?.PersonBirthdate != null ? String.valueOf(opp.Account.PersonBirthdate) : '');
    }
}